name: smattodo
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  build_runner: ^2.4.8
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  logger: ^2.0.2+1
  stomp_dart_client: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
